### ISSUE TITLE
Can't set charging limits

### ISSUE THREAD

**Issue by ptrtech1** [dahlb/ha_kia_hyundai#133]
Please check Services, Known Bug / Issues and Troubleshooting over here first: https://github.com/dahlb/ha_kia_hyundai/blob/master/README.md
**Region and Brand of car**
US Kia EV9

**Describe the bug**
Sending command to set charging limits is producing an error

**Debug logs if an error occurred**

Outlined here: https://github.com/dahlb/ha_kia_hyundai/blob/master/README.m

**To Reproduce**
1. Go to Automation
2. Action: set charging limits
3. Set and run automation

**Expected behavior**
Sets without error

**Screenshots**
Attached
![IMG_8297](https://github.com/dahlb/ha_kia_hyundai/assets/45398604/7d7b584f-cf20-4900-912b-81746421126e)

**Additional context**

**Comment by dahlb** [comment]
Try it without setting the device id parameter, that's only used if you have two cars

**Comment by ptrtech1** [comment]
> Try it without setting the device id parameter, that's only used if you have two cars

That worked.
