### ISSUE TITLE
Improvement: debug sensors

### ISSUE THREAD

**Issue by jakecolman** [dahlb/ha_kia_hyundai#50]
The API returns all sorts of interesting data such as whether the car is financed, the car's color, etc.  Might be nice to have that data included as a device attribute, assuming HA allows for free-form device attributes.

**Comment by dahlb** [comment]
that is a great idea, I can see that helping with debug so people don't have to add logging for most issues. there is already a sensor called DATA that holds the mapped values from the api responses.  I'm thinking of adding a second one to include the raw responses and naming them "DEBUG MAPPED DATA" and "DEBUG RAW DATA"

**Comment by jakecolman** [comment]
I was thinking about having it on the Device Attributes view in HA but,
after looking at it, you can't simply add your own attributes.  I didn't
notice the DATA sensor.  Cool idea!  Having two is an even better idea!

**Comment by dahlb** [comment]
https://github.com/dahlb/ha_kia_hyundai/commit/8d59100eba4a597cf9c8efa013873fc42bcf47eb should add that new raw sensor and improve the readability of the mapped sensor, for safety I stringified the raw data.  but if can be copied and pasted into something like [jsonlint.com](https://jsonlint.com/) for easy reading.

Please let me know if it works for you, always great to get confirmation it works on another setup :) and if you see any raw data that is missing from your sensors and you would find useful open tickets :)

**Comment by jakecolman** [comment]
Looks good.  Thanks.
