### ISSUE TITLE
Add Sensor for "Distance to Empty"

### ISSUE THREAD

**Issue by jakecolman** [dahlb/ha_kia_hyundai#51]
**Is your feature request related to a problem? Please describe.**
"Distance to Empty" is available in from the API and would be a useful addition to the sensor list.

**Include the logs of the end point from Data in HA if this is a sensor**

					"distanceToEmpty": {
						"value": 397,
						"unit": 3
					},

**Comment by dahlb** [comment]
that sensor already exists for other region/brands, it just wasn't mapped correctly for non-ev vehicles in US Kia.  https://github.com/dahlb/ha_kia_hyundai/commit/9658a2eb99f3d7811ef73f15809ed6982cd9c5f3 should fix that.

**Comment by jakecolman** [comment]
I downloaded master and "niro range by fuel" and "niro range total" now
appear as sensors.  This issue can be closed.  Thanks.
