### ISSUE TITLE
HA reports range in miles/km unpredictably

### ISSUE THREAD

**Issue by lxqikrana** [dahlb/ha_kia_hyundai#54]
USA Hyundai Ioniq 5

**Describe the bug**
Home Assistant sometimes reports range in miles, other times in kilometres.

**Expected behavior**
Report range in miles only

**Screenshots**
![image](https://user-images.githubusercontent.com/12616210/156940548-4efc0498-ec98-4629-85fb-c12290301cb0.png)

**Comment by dahlb** [comment]
sorry but that looks like a lovelace (dashboard) issue, not part of this integration. easiest way to see all the integration provided data directly is go to the list of integrations then click where is says 1 device in the Kia/Hyundai car you should see a list like the before with all the distance in your home assistant preferred unit 
![Screenshot_20220303-064104](https://user-images.githubusercontent.com/54117/156951888-09aed40c-f104-455f-937d-d23706eafc0f.png)
d
