### ISSUE TITLE
Add start/stop charge and set charge limits for Hyundai USA

### ISSUE THREAD

**Issue by FuzzyMistborn** [dahlb/ha_kia_hyundai#55]
**Is your feature request related to a problem? Please describe.**

Per the readme, starting/stopping the charge and setting the charge limit is not available in the USA for Hyundai.  I'd like this added.

**Describe the solution you'd like**

Being able to start/stop the charge and setting the charge limit.

**Include the logs of the end point from Data in HA if this is a sensor**

**Describe alternatives you've considered**

**Additional context**

Not sure if this is some kind of API limitation or what.  If it is I totally understand.  Just would like to be able to control this in HASS for my Ioniq 5.

**Comment by dahlb** [comment]
Sorry, I only ported what functionality I found documented in this [node project](https://github.com/Hacksore/bluelinky) I only have access to a Kia US account, so I just don't have any access to reverse engineer the api like i did with the Kia US API.  

Somebody with access to a Hyundai US account can pick up this ticket and help with a PR to add this functionality.

**Comment by dahlb** [comment]
The Hyundai mobile has some invalid encoding issues so it's not easily reverse engineered.

I would need a network log of the api interactions generated using the Hyundai US web portal [ie](https://developer.chrome.com/docs/devtools/network/) Another option would be to set a temporary password on your account and let me use it while prototyping the new api implementation, though to be clear there is no guarantee that is can be reverse engineered.  Unfortunately I only have about 2 hours a day available for side projects like this one so I can't walk you through how to log the api interactions.  

If you can document the network activity when you log into the web portal for Hyundai I can work on a script to test a new implementation; login is always the most complex and difficult step, normally after login everything else is pretty simple.

**Comment by FuzzyMistborn** [comment]
I'll see what I can do if I have some free time.  Like you little bit time limited, appreciate the guidance though!

**Comment by stephenjamieson** [comment]
@dahlb, someone got the API endpoints from the mobile app and I added it to this project - https://github.com/stephenjamieson/hyundai_kia_connect_api/commit/2d3bd1dcb2380aed4a2c319a77681f5feed8d73b, just in case you wanted to use it here.
