### ISSUE TITLE
Deprecated HA warning in 2022.11.2 for is_metric

### ISSUE THREAD

**Issue by Linwood-F** [dahlb/ha_kia_hyundai#63]
USA, Kia, EV6, Wind AWD

After updating to 2022.11.2 (from 2022.10.x) received a deprecated warning as below: 

`Logger: homeassistant.helpers.frame
Source: helpers/frame.py:77
First occurred: 5:51:48 PM (1 occurrences)
Last logged: 5:51:48 PM

Detected integration that accesses the `is_metric` property of the unit system. This is deprecated and will stop working in Home Assistant 2023.1. Please adjust to use instance check instead.. Please report issue to the custom integration author for ha_kia_hyundai using this method at custom_components/ha_kia_hyundai/__init__.py, line 161: if hass.config.units.is_metric:`

**Comment by dahlb** [comment]
thanks for filing this, I'll try to fix this in the next week or two
