### ISSUE TITLE
Add EV battery SoC to default dashboard card

### ISSUE THREAD

**Issue by cure1245** [dahlb/ha_kia_hyundai#75]
**Is your feature request related to a problem? Please describe.**

I've noticed that the EV Battery SoC for my Kia EV6 is not present anywhere on the default dashboard card.

**Describe the solution you'd like**

It would be great if that information was visible from the default dashboard,

**Comment by dahlb** [comment]
<img width="313" alt="Screenshot 2023-05-11 at 8 31 16 PM" src="https://github.com/dahlb/ha_kia_hyundai/assets/54117/13ea4da9-88d1-497d-b1bb-8647a3e8fcc8">

the ev battery should look like this on the device integration, I don't know anything about the default dashboard cards.  Are you unable to see the ev battery level?

**Comment by cure1245** [comment]
I just saw it... I swear I checked like 6 times!
