### ISSUE TITLE
"unexpected error" after change at Hyundai/Kia

### ISSUE THREAD

**Issue by GarryG** [dahlb/ha_kia_hyundai#83]
Sign-on with bluelink service fails since change on the server side of Hyundai.

See here for Debug infos from the Hyundai Kia Connect API Project:

https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/issues/348

**To Reproduce**
Formerly working connection fails, as does any attempt to create a new integration

**Additional context**
This project seems to have fixed the issue for now ...

https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/releases/tag/v3.3.8

Edit: More changes and fixes, last version I saw was 3.3.11

**Comment by dahlb** [comment]
this integration only supports us region with kia brand, for other regions/brands use https://github.com/Hyundai-Kia-Connect/kia_uvo

**Comment by ludditus-RPI** [comment]
Just curious, is there a reason why Hyundai support is not planned?  The name of the project is misleading if it's only meant to work with Kia. Or is it only US Hyundai vehicles that won't be supported?

**Comment by dahlb** [comment]
it used to support hyundai but feature was removed due to neglect and lack of interested developers.
I haven't renamed the repo because it is a large effect for low return.  
Would you like to add support for hyundai as a developer?
