### ISSUE TITLE
won't load

### ISSUE THREAD

**Issue by wystewart** [dahlb/ha_kia_hyundai#85]
has been able to load for several months.  this is for canada.

             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ha_kia_hyundai/__init__.py", line 214, in async_setup_entry
    api_cloud_instance = api_cloud_class(
                         ^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not callable

**Comment by dahlb** [comment]
this is a duplicate of https://github.com/dahlb/ha_kia_hyundai/issues/73
